### ISSUE TITLE
Initial decisions we need to make

### ISSUE THREAD

**Issue by ClimbsRocks** [CloudBalance/CloudBalance#1]
1. Asana or Waffle
2. Git strategy- rebase?

**Comment by conrad** [comment]
For me,
1. Waffle looks cool, but we're already signed up with Asana--don't care
   which, too much
2. yes, rebase

---

Matt Conrad
mmconrad@gmail.com
615.347.0889

**Comment by zheshishei** [comment]
1. I'm slightly leaning towards waffle
2. rebase is fine

**Comment by ClimbsRocks** [comment]
Waffle and rebase it is.

Closed!

**Comment by csreyes** [comment]
I'm interested in trying out waffle
