### ISSUE TITLE
Decide what sort of router should be used to go between pages

### ISSUE THREAD

**Issue by conrad** [CloudBalance/CloudBalance#21]
React/Flux does not have a router.  I have received suggestions to use the Backbone router to move between Signup, Login, and Main Page

**Comment by ClimbsRocks** [comment]
I'm just starting on React today, so apologies for my ignorance. Wouldn't we just use the same routing we're using on the server? Apologies if this is a stupid question; I'm still waiting for the coffee to kick in :)

**Comment by conrad** [comment]
We can do a multi-page app.  I have set up the other pages, but I just haven't connected the about page, which will require a couple ajax calls to navigate there and back.

**Comment by ClimbsRocks** [comment]
We've figured out the routing, using standard Javascript functions.
