### ISSUE TITLE
Server to External API Library

### ISSUE THREAD

**Issue by zheshishei** [CloudBalance/CloudBalance#4]

**Comment by zheshishei** [comment]
Functionality (CRUD):
- Add a File (Create)
- Retrieve list of Files (Read)
- Retrieve one File (Read)
- Remove a File (Delete)

**Comment by zheshishei** [comment]
Methods:
- GetFileList(service)
- AddFile(service, fileObject?)
- RemoveFile(service, fileId)

**Comment by ClimbsRocks** [comment]
great job, @zheshishei !
