### ISSUE TITLE
Client to Server API Endpoints

### ISSUE THREAD

**Issue by ClimbsRocks** [CloudBalance/CloudBalance#5]
1. Get file lists from both services. 
   Send: 
   Type: Get
   data:getAllFileLists
   Receive: json file lists, where both file lists are in the same format
2. Move file from one location to another
   Send: 
   Type: Post
   data: fileID, fromLocation (path most likely), toLocation (again, a path most likely). fromService (service name), toService (service name)
   Receive: fully updated file lists from each service. This will be the complete file list from each service to start with. 
3. Signin and authetication
   Send: 
   Type: Post
   data: username, password. This will look up the tokens for each service in the database. 
   Receive: authentication stuff. 
4. Signup
   Send: username
   Receive: if that username is available/fits our requirements
   Send: username and password for CloudBalance
   Receive: authentication stuff
   Send: oauth info for both services
   Receive: more authentication stuff.

**Comment by conrad** [comment]
The POST requests for moving files should include the locations/directories within services of both where the file is moving to and where it's coming from--which is represented in this issue but did not make it into the files yet

**Comment by conrad** [comment]
Will folders have a fileID, or a some other identifier?

**Comment by ClimbsRocks** [comment]
great note, matt. i'm not sure what kind of identifier our folders will have; we'll have to get that info from @zheshishei or @csreyes. 

I just added that in as a note to my most recent commit
